name: Test


on: [push]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ls2
        run: |
          chmod +x script.sh
          ./script.sh

